# Stage-1 dependencies
FROM node:latest as dep

RUN mkdir /app
WORKDIR /app

ADD package.json .
RUN ["yarn"]

# Stage-2 final image
FROM node:lts-alpine

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install packages for node-canvas
RUN apk --no-cache --virtual .build-deps add \
        python \
        make \
        g++ \
    && apk --no-cache --virtual .canvas-build-deps add \
        build-base \
        cairo-dev \
        jpeg-dev \
        pango-dev \
        giflib-dev \
        pixman-dev \
        pangomm-dev \
        libjpeg-turbo-dev \
        freetype-dev \
    && apk --no-cache add \
        pixman \
        cairo \
        pango \
        giflib \
    && apk del .build-deps \
    && apk del .canvas-build-deps

COPY --from=dep /app/node_modules /app/node_modules
RUN ["yarn", ""]

# Bundle app source
COPY . /app
# RUN yarn build

# Clear the cache
RUN yarn cache clean

EXPOSE 3000
CMD [ "yarn", "dev" ]