# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "vs2017-win2016"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "^8.12.0"
    displayName: "Install Node.js"

  - script: |
      yarn
    displayName: "Install Dependencies"

  - script: |
      yarn test:unit
    displayName: "Run Unit Tests"

  - script: |
      yarn coverage
    displayName: "Publish Test Result"
