version: "3.7"

services:

  mobile:
    build:
      context: ./mobile
      dockerfile: ./mobile/Dockerfile
    ports:
      - 4040:4040
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4040
    volumes:
      - ./mobile:/app

  admin:
    build:
      context: ./admin
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4000
    volumes:
      - ./admin:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin