FROM node:lts-alpine

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install packages for node-canvas
RUN apk add --no-cache --virtual .build-deps alpine-sdk python \
 && npm install --production --silent \
 && apk del .build-deps

COPY package.json /app/
COPY yarn.lock /app/
RUN yarn install

# Bundle app source
COPY . /app
RUN yarn build

# Clear the cache
RUN yarn cache clean

EXPOSE 3000
CMD [ "yarn", "start" ]