FROM node:lts

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install packages for node-canvas
RUN sudo apt install build-essential \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev

COPY package.json /app/
COPY yarn.lock /app/
RUN yarn install

# Bundle app source
COPY . /app
RUN yarn build

# Clear the cache
RUN yarn cache clean

EXPOSE 3000
CMD [ "yarn", "start" ]