FROM node:lts

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install packages
RUN apt update && apt upgrade

COPY package.json /app/
COPY yarn.lock /app/
RUN yarn install

# Bundle app source
COPY . /app
# RUN yarn build

# Clear the cache
# RUN yarn cache clean

EXPOSE 3000
CMD [ "yarn", "dev" ]